### ISSUE TITLE
Translate for multi values fields

### ISSUE THREAD

**Issue by Mostafa-Ashmawy** [logstash-plugins/logstash-filter-translate#19]
Mainly we are trying to add a field productName to a document before indexing it based on the document productId using the translate plugin and a yaml dictionary file containing a mapping (productId:productName). We couldn't apply the filter to all the elements of that field. 
We would like to have something like that where i is [0, basketInfos.length]
      translate{
        field => "[basketInfos][i][productId]"
        destination => "[basketInfos][i][productName]"
        dictionary_path=> "/home/ms/logstash-2.1.0/dictionary.yaml"
        exact => true
    }

And this is a snippet of the dictionary.yaml file
"378801434": Product-111
"417509627": Product-112
"ov393627130": Product-113

**Comment by CSUMBmWall** [comment]
I would also benefit from this feature.  

I have a field with an array of values I need translated. Since translate only works on the first value, I renamed all of the fields dynamically to input_["value"]. Now I can't use translate on them because it requires a specific field, and I have any number of these fields that were once in an array, and are now named according to their value.

If I could use translate on an array, could translate according to a tag, instead of a field, or if I could use a wildcard/regex/pattern for the field value, I would be a happy camper.

**Comment by markwalkom** [comment]
Multi-value field - arrays - support would be unreal.

**Comment by rparkhunovsky** [comment]
Looks like it's addressed in https://github.com/logstash-plugins/logstash-filter-translate/pull/15 but has been stale for some time.

**Comment by guyboertje** [comment]
Seems like this config would express the intent:
```
translate {
  field => "[productId]"
  destination => "[productName]"
  foreach => "[basketInfos]"
  dictionary_path=> "/home/ms/logstash-2.1.0/dictionary.yaml"
  exact => true
}
```
I can implement this and I think this is useful in the other enrichment filters too.

**Comment by guyboertje** [comment]
Closing, will be covered with PR #67
