### ISSUE TITLE
dictionary example type

### ISSUE THREAD

**Issue by wols** [logstash-plugins/logstash-filter-translate#43]
The dictionary config validates a hash, but the example shows a array?
https://github.com/logstash-plugins/logstash-filter-translate/blob/master/lib/logstash/filters/translate.rb#L54

**Comment by jordansissel** [comment]
I can explain:

Before Logstash 1.2, the syntax for a hash in the Logstash config was similar to list/array using `[ ... ]` notation: `[ "key", "value", "key2", "value2", ... ]`

Since Logstash 1.2, we added the more familiar curly-brace hash syntax `{ "key" => "value", ... }`

The old syntax has been kept for backwards compatibility.

So this syntax:

```
  #         dictionary => [ "100", "Continue",
  #                         "101", "Switching Protocols",
  #                         "merci", "thank you",
  #                         "old version", "new version" ]
```

Is still valid. The config still parses it as a hash as if it were `{ "100" => "Continue", "101" => "Switching Protocols", ... }`

**Comment by jordansissel** [comment]
We should update the example to use the newer syntax, but the older syntax is still working.

**Comment by wols** [comment]
I understand, THX!

**Comment by elvarb** [comment]
@jordansissel are there any plans to phase out the old syntax? I see both used all the time and I have never been sure why it is like that, now I know :)

**Comment by jordansissel** [comment]
@elvarb I personally don't have much strong incentive to remove it. I think we can probably remove it once our docs stop using it for examples, so maybe the first step for phasing it out is to update all the docs? I'm open to discussing this in an issue on the logstash repo. I think we can find a path forward to help users migrate to the "new (since Logstash 1.2) hash syntax without burdening them too much.

Additionally, many older blog posts and articles may use the older syntax, and removing the old syntax support would break all those configs.
