### ISSUE TITLE
Deleted value in dynamic config don't fallback

### ISSUE THREAD

**Issue by amaury-d** [logstash-plugins/logstash-filter-translate#54]
- Version: logstash-filter-translate-3.0.4
- Operating System: CentOS 7.2.1511
- Config File (if you have sensitive info, please remove it):
```
      translate {
		field => "application"
		dictionary_path => "/tech/logstash/conf.d/toolbox/config.yml"
		destination => "key"
		fallback => "log"
		refresh_interval => 30
	}
```
- Sample Data:
config.yml:
```
    placeholder: placeholder
    foo: bar
```
- Steps to Reproduce:

1. Start logstash
2. Inject msg with application=foo, it translates to application=bar, no problem here
3. Then delete the line `foo:bar` from config
4. After dynamic refresh, application=foo keeps being translated to application=bar instead of fallback to application=log

**Comment by guyboertje** [comment]
This behaviour is has been the default since 10 Sep 2014. The dictionary is merged on reload so keys and values deleted on file will not be removed from the in-memory dictionary.

I suggest that, instead of deleting, you change the value to `deleted-translation` and then add a conditional block that replaces that value with your fallback.

**Comment by amaury-d** [comment]
For information, commit e33dc0a7c156d85ffde43174210dfaae1d5f19c5 added the option 'refresh_behaviour'
